env:
  es6: true
  node: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/explicit-module-boundary-types': off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
